## YAML Template.
---

systemLog:
   verbosity: 1
   quiet: false
   traceAllExceptions: false
   #syslogFacility: <string>
   path: C:\mongo\logs\mongod.log
   logAppend: true
   logRotate: rename
   destination: file
   timeStampFormat: ctime
#   component:
#      accessControl:
#         verbosity: <int>
#      command:
#         verbosity: <int>   
   
storage:
   dbPath: C:\mongo\data\db
#   indexBuildRetry: <boolean>
#   repairPath: <string>
   journal:
      enabled: true
#      commitIntervalMs: <num>
#   directoryPerDB: <boolean>
#   syncPeriodSecs: <int>
   engine: mmapv1
#   mmapv1:
#      preallocDataFiles: <boolean>
#      nsSize: <int>
#      quota:
#         enforced: <boolean>
#         maxFilesPerDB: <int>
#      smallFiles: <boolean>
#      journal:
#         debugFlags: <int>
#         commitIntervalMs: <num>
#   wiredTiger:
#      engineConfig:
#         cacheSizeGB: <number>
#         journalCompressor: <string>
#         directoryForIndexes: <boolean>
#      collectionConfig:
#         blockCompressor: <string>
#      indexConfig:
#         prefixCompression: <boolean>
#   inMemory:
#      engineConfig:
#         inMemorySizeGB: <number>
            
net:
   port: 27017
   bindIp: localhost
   maxIncomingConnections: 65536
#   wireObjectCheck: <boolean>
#   ipv6: <boolean>
#   unixDomainSocket:
#      enabled: <boolean>
#      pathPrefix: <string>
#      filePermissions: <int>
#   http:
#      enabled: <boolean>
#      JSONPEnabled: <boolean>
#      RESTInterfaceEnabled: <boolean>
#   ssl:
#      sslOnNormalPorts: <boolean>  # deprecated since 2.6
#      mode: <string>
#      PEMKeyFile: <string>
#      PEMKeyPassword: <string>
#      clusterFile: <string>
#      clusterPassword: <string>
#      CAFile: <string>
#      CRLFile: <string>
#      allowConnectionsWithoutCertificates: <boolean>
#      allowInvalidCertificates: <boolean>
#      allowInvalidHostnames: <boolean>
#      disabledProtocols: <string>
#      FIPSMode: <boolean>
      
#   compression:
#      compressors: <string>

#security:
#   keyFile: <string>
#   clusterAuthMode: <string>
#   authorization: <string>
#   transitionToAuth: <boolean>
#   javascriptEnabled:  <boolean>
#   redactClientLogData: <boolean>
#   sasl:
#      hostName: <string>
#      serviceName: <string>
#      saslauthdSocketPath: <string>
#   enableEncryption: <boolean>
#   encryptionCipherMode: <string>
#   encryptionKeyFile: <string>
#   kmip:
#      keyIdentifier: <string>
#      rotateMasterKey: <boolean>
#      serverName: <string>
#      port: <string>
#      clientCertificateFile: <string>
#      clientCertificatePassword: <string>
#      serverCAFile: <string>
#   ldap:
#      servers: <string>
#      bind:
#         method: <string>
#         saslMechanism: <string>
#         queryUser: <string>
#         queryPassword: <string>
#         useOSDefaults: <boolean>
#      transportSecurity: <string>
#      timeoutMS: <int>
#      userToDNMapping: <string>
#      authz:
#         queryTemplate: <string>

#operationProfiling:
#   slowOpThresholdMs: <int>
#   mode: <string>

#replication:
#   oplogSizeMB: <int>
#   replSetName: <string>
#   secondaryIndexPrefetch: <string>
#   enableMajorityReadConcern: <boolean>

#sharding:
#   clusterRole: <string>
#   archiveMovedChunks: <boolean>

#auditLog:
#   destination: <string>
#   format: <string>
#   path: <string>
#   filter: <string>

#snmp:
#   subagent: <boolean>
#   master: <boolean>